apiVersion: v1
kind: Service
metadata:
  name: {{ include "jvmlens.fullname" . }}
  labels:
    {{- include "jvmlens.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jvmlens.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.target.port }}
      targetPort: http
    {{- if .Values.summary.enabled }}
    - name: summary
      port: {{ .Values.summary.port }}
      targetPort: summary
    {{- end }}
